### PR TITLE
Add 6.0.2 version support

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by dscharrer** [comment]
[The setup data version has not changed in Inno Setup 6.0.2](https://github.com/jrsoftware/issrc/blob/is-6_0_2/Projects/Struct.pas#L36) (the format is the same as in 6.0.0).

You can also see this by checking the Inno Setup downloads:

    $ ./innoextract --test ../is/innosetup-6.0.2.exe 
    Testing "Inno Setup" - setup data version 6.0.0 (unicode)
    […]

**Comment by diorcety** [comment]
I misread my output. Sorry. When do you plan to release a new version?

**Comment by dscharrer** [comment]
Hopefully soon, just have a bunch of things I need to catch up on.

**Comment by bovirus** [comment]
@dscharrer 

Could you pelase make the temporary build for Windows/Linux?

Otherwise we cannot enabled to test it.

**Pull request closed without merging**
