### PR TITLE
Add support for Inno Setup 6.3.0+

### LINKED ISSUE #173: New InnoSetup version just released
The new InnoSetup version 6.3.1 has been released two days ago.
Unfortunately Innoextract 1.9 is not able to open this kind of packages.

Is there any hope for an update?
Thanks

### PR DESCRIPTION
**Pull request by crackedmind**
Fix #173

### CODE REVIEW

**Comment by JustDj-Git** [comment]
@crackedmind Hi, bud.  Could you please compile your version and upload it somewhere?

**Comment by crackedmind** [comment]
@JustDj-Git  build for windows x64
[innoextract.zip](https://github.com/user-attachments/files/16166986/innoextract.zip)

**Comment by leochou0729** [comment]
Please support Inno Setup 6.3.0! Thanks!

**Comment by kalebo** [comment]
@crackedmind thanks for taking the time to patch in support. I built from crackedmind/innoextract@ef31ac4 and it works for the files I needed (although I did have to add a missing include for `unordered_map`). 

Is there a reason this PR was closed @dscharrer? It would be nice to have these changes mainlined since the same ci pipelines failing here are also failing on master AFAICT.

**Comment by crackedmind** [comment]
> @crackedmind thanks for taking the time to patch in support. I built from [crackedmind/innoextract@ef31ac4](https://github.com/crackedmind/innoextract/commit/ef31ac4) and it works for the files I needed (although I did have to add a missing include for `unordered_map`).
> 
> Is there a reason this PR was closed @dscharrer? It would be nice to have these changes mainlined since the same ci pipelines failing here are also failing on master AFAICT.

i closed PR myself. because @dscharrer won't merge it. you can try my fork, or some forks based on mine.

**Comment by kalebo** [comment]
Do you mean that @dscharrer had explicitly said that he won't merge it or that he hasn't been around to merge it? E.g., I see that a repo owner deleted one of your comments @crackedmind; was that related?

**Comment by God-damnit-all** [comment]
@crackedmind Could you please respond to @kalebo's comment?

**Pull request closed without merging**
