### PR TITLE
Including original spec file from OSB

### PR DESCRIPTION
**Pull request by moceap**
As explained in http://constexpr.org/innoextract/#packages

### CODE REVIEW

**Comment by moceap** [comment]
Updatet @dscharrer

**Comment by moceap** [comment]
@dscharrer U

**Comment by moceap** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1239267

**Comment by dscharrer** [comment]
Hi, thanks for you efforts.

However, I do not thing distribution-specific packaging scripts belong in the main repo. I also don't see the need for having multiple .spec files on my end when the differences are minor between RPM distributions.

Sources for the packages I maintain are tracked at https://github.com/arx/ArxPackages/blob/master/innoextract/ - I have added some of your changes to https://github.com/arx/ArxPackages/blob/master/innoextract/rpm/innoextract.spec

Looking forward to seeing an innoextract package in Fedora.

**Comment by moceap** [comment]
Fixed .. and long cmake line :)

**Comment by moceap** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1239267#c1

**Pull request closed without merging**
