### PR TITLE
implement simple --include option (#12)

### PR DESCRIPTION
**Pull request by a-detiste**
this option can be repeated

### CODE REVIEW

**Comment by dscharrer** [comment]
Thanks. I'll hopefully get around to releasing a new version during the weekend.

If you want, I can add you to the readme under "additional contributors" or something.

**Comment by a-detiste** [comment]
I guess it will be v1.5 ? Not 1.4.1

Use of this is already implemented, with a fallback if user stil uses v1.4.

http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/commit/?id=ae8d53d68cece528ba785283d7be7cb96d1be911

> If you want

No it's not really needed :smile:

**Comment by dscharrer** [comment]
> I guess it will be v1.5 ? Not 1.4.1

Yes.

> No it's not really needed :smile:

Your choice.

**Comment by dscharrer** [comment]
> Use of this is already implemented, with a fallback if user stil uses v1.4.

Btw, you can combine `--silent` with `--version` to get only the version number - then you don't need to check the substring.

**Comment by a-detiste** [comment]
Thanks, should have read the man page.

This will propably stay that way till Debian Stretch is released; this way G-D-P and/or innoextract can be individually backported to Jessie/apt-pinned from Stretch if someone cares.

**Comment by a-detiste** [comment]
@dscharrer @smcv

I managed to use upcoming innoextract 1.5 in a way to allways *only* extract the needed files.

`game-data-packager` already has to manage a list of files provided by the Innosetup archive (or any kind of archive), so in most cases it forward this list as-is to `innoextract`; it can also add a prefix in front on each file or add a loose file like `/app/manual.pdf` to the mix if applicable.

So `--exclude` is not needed here.

All of that depends on this current Innoextract behaviour: the `--lowercase` is processed before the `--include`.

Is this ok to keep it this way in the future ?

http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/commit/?id=6ea03877f9b7eeb3231832ab917f723db2f74f46

**Comment by dscharrer** [comment]
> So `--exclude` is not needed here.

Nice.

> All of that depends on this current Innoextract behaviour: the --lowercase is processed before the --include.
> 
> Is this ok to keep it this way in the future ?

Yes. Maybe it makes sense to always match case insensitively? These are filenames meant for Windows after all.

**Comment by a-detiste** [comment]
> Maybe it makes sense to always match case insensitively?

Maybe the same filename exists in uppercase / lowercase in two different places and some script only need one. Anyway, this `--include` thing would mostly be called by scripts that know in advance what to expect in an archive.

**Pull request merged**
